### ISSUE TITLE
Dead links in README.MD

### ISSUE THREAD

**Issue by user8547** [coreruleset/plugin-registry#28]
These two are dead links linked in README.MD:

```
https://github.com/coreruleset/ghost-rule-exclusions-plugin
https://github.com/coreruleset/performance-plugin
```

**Comment by EsadCetiner** [comment]
@user8547 The links are dead because the repositories are set to private.

**Comment by EsadCetiner** [comment]
@user8547 I've made it clearer that these plugins are set to private in PR https://github.com/coreruleset/plugin-registry/pull/29 Hopefully this will prevent further confusion in the future.
